name: Update Projects Data 

on:
  push:
    branches:
      - master 
  schedule:
    - cron: "0 0 * * 0"   # every sunday 00:00 UTC
  workflow_dispatch: 

permissions:
  contents: write
  pages: write
  repository-projects: write

jobs:
  update-projects: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive  

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install deps
        run: pip install requests

      - name: Generate projects.json
        env:
          GH_DEPLOY: ${{ secrets.GH_DEPLOY }}
        run: |
          python prabhsuratsinghblog/scripts/update_pinned_projects.py

      - name: Commit & push data
        env:
          GH_DEPLOY: ${{ secrets.GH_DEPLOY }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git remote set-url origin https://x-access-token:${GH_DEPLOY}@github.com/prabhsuratsingh/blog.git
          git add data/projects.json
          git commit -m "update pinned projects" || echo "no changes"
          git push origin HEAD:master


      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Build
        run: |
          cd prabhsuratsinghblog
          hugo
      
      - name: Commit public submodule
        working-directory: prabhsuratsinghblog/public
        env:
          GH_DEPLOY: ${{ secrets.GH_DEPLOY }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git checkout master
          git add .
          git commit -m "deploy" || echo "no changes"

          if [ -z "$GH_DEPLOY" ]; then
            echo "‚ùå GH_DEPLOY is missing!"
            exit 1
          fi

          git remote set-url origin https://x-access-token:${GH_DEPLOY}@github.com/prabhsuratsingh/prabhsuratsingh.github.io.git

          git push origin HEAD:master





